name: Pull Request Conflict Check
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for merge conflicts
        run: |
          git fetch origin main
          git merge --no-commit --no-ff origin/main || echo "Merge conflicts detected"

      - name: Notify Discord
        if: failure()
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Merge conflicts detected in pull request!"}' YOUR_DISCORD_WEBHOOK_URL