name: Pull Request Conflict Check
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for merge conflicts
        run: |
          git fetch origin main  # Change 'main' to your default branch if necessary
          if ! git merge --no-commit --no-ff origin/main; then
            echo "Merge conflicts detected"
            exit 1  # Exit with a non-zero status to indicate failure
          fi

      - name: Notify Discord
        if: failure()  # This will run if the previous step fails
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Merge conflicts detected in pull request!"}' ${{ secrets.DISCORD_WEBHOOK_URL }}